# Generated by Django 3.2.6 on 2021-09-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='logo',
            field=models.FileField(default='whale.png', upload_to=''),
        ),
    ]
