# Generated by Django 4.0.6 on 2022-07-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner', models.ImageField(default='images/mood_banners/default.png', upload_to='images/mood_banners/')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='banner',
            field=models.ImageField(default='images/song_banners/default.png', upload_to='images/song_banners/'),
        ),
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.ManyToManyField(to='songs.mood'),
        ),
    ]
