# Generated by Django 4.0.6 on 2022-07-14 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 14, 12, 57, 8, 750431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
