# Generated by Django 4.0.6 on 2022-07-13 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0002_mood_alter_song_banner_song_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('banner', models.ImageField(default='images/genre_banners/default.png', upload_to='images/genre_banners/')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='favourite_by',
            field=models.ManyToManyField(related_name='favourite_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(to='songs.genre'),
        ),
    ]
