# Generated by Django 4.0.6 on 2022-07-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_upload_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-upload_time']},
        ),
    ]
