# Generated by Django 4.0.6 on 2022-07-13 03:19

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0003_genre_song_favourite_by_alter_mood_name_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2022, 7, 13, 3, 19, 15, 959455, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='favourite_by',
            field=models.ManyToManyField(blank=True, related_name='favourite_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='songs', to='songs.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.ManyToManyField(blank=True, related_name='songs', to='songs.mood'),
        ),
    ]
