# Generated by Django 4.0.6 on 2022-07-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_comment_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='banner',
        ),
    ]
